### ISSUE TITLE
Alpha v0.5 - Missing chat

### ISSUE THREAD

**Issue by Navitron** [Lemon-King/ToS-LKChat#10]
Chat messages not showing up at all with the newest version.

**Comment by patsi91** [comment]
I'd like to add that in my enviroment of addons (CW addons and excrulons addons) version 0.5 does not seem to load at all because /lkc and /lkchat  do nothing at all when previously they would open the option screen of lkchat.

**Comment by Lemon-King** [comment]
Fixed now with v0.5a, for some reason after I made the push today client events began sending out of order causing the addon to fail after initialization. I've reverted any messaging pausing at load time.
