### ISSUE TITLE
Critical bug.

### ISSUE THREAD

**Issue by Dalamar6** [Lemon-King/ToS-LKChat#8]
If you spam wasdawdasdaw or whatever from the trashbad chat system's failness, the addon blocks and reports yourself, resulting in a crash, and you can no longer log in with the addon installed.

Addon should clearly ignore yourself and party members. Also, it's too sensitive.

**Comment by Lemon-King** [comment]
Do you have a copy of the line you typed? Or at least a close example?

**Comment by Dalamar6** [comment]
That was the example, I use wasd to move. I don't have the exact line, it was last night.

**Comment by Lemon-King** [comment]
Could you try getting me a repo case?
I've also updated my development copy to ignore the player, for some reason that wasn't checked.

**Comment by Dalamar6** [comment]
What do you mean repo case? By the way that crash also hit my friend last night when I hit enter, he crashed exactly when I did and had to delete the addon too, so I think it's not just the player.

**Comment by Lemon-King** [comment]
A reproduction case, where you can reproduce the bug more than once under the same or different conditions.
So a few more things I'll need if I want to repo it on my end.
Were you in a dungeon or world zone?
How big was your group?
Did you put the message in say (normal), party, guild, whisper (group whisper), shout?

**Comment by Dalamar6** [comment]
Starter area messing with the dysfunctional keybind system, chatting with a friend (in friendlist) in a 2 man party chat. 0.4a, also have betterquest and tos-lua-addons-excrulon-20160411-02 if those matter.

How would I reset lkchat's data so I can log in with it installed again btw?

**Comment by Lemon-King** [comment]
I'm not sure why the client is crashing today. I cleaned out all the addons I had running.

**Comment by Lemon-King** [comment]
Question, where does the client crash when you try to log in? What screens do you get past?

**Comment by Dalamar6** [comment]
It was crashing last night after selecting a character. Works today with lkchat installed oddly.

**Comment by Lemon-King** [comment]
That is odd, well I pushed a new version (v0.4b) which has a check in place for character name.

Thanks for all the reports, feel free to PM me on the TOS forums.
